In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
from glob import glob
import matplotlib.pyplot as plt
import glob

from keras.models import Sequential
from keras.preprocessing import image
from keras.layers import Dense, InputLayer, Conv2D, MaxPool2D, Flatten
    
from sklearn.model_selection import train_test_split
from skimage.transform import resize

Using TensorFlow backend.


In [2]:
data = pd.read_csv('Class.csv')

In [3]:
X = pd.DataFrame(columns=['Filename','Label'])
for img_name in data.Label:
    CommonName = data[data['Label'] == img_name]
    print('training\\'+img_name+'\\')
    for file_name in glob.iglob('training\\'+img_name+'\\*.*', recursive=True):
       print(file_name)
       X=X.append({'Filename':file_name,'Label':img_name},ignore_index=True)

training\n0\
training\n0\n0018.jpg
training\n0\n0019.jpg
training\n0\n0020.jpg
training\n0\n0021.jpg
training\n0\n0022.jpg
training\n0\n0023.jpg
training\n0\n0024.jpg
training\n0\n0025.jpg
training\n0\n0026.jpg
training\n0\n0027.jpg
training\n0\n0028.jpg
training\n0\n0029.jpg
training\n0\n0030.jpg
training\n0\n0031.jpg
training\n0\n0032.jpg
training\n0\n0033.jpg
training\n0\n0034.jpg
training\n0\n0035.jpg
training\n0\n0036.jpg
training\n0\n0037.jpg
training\n0\n0038.jpg
training\n0\n0039.jpg
training\n0\n0040.jpg
training\n0\n0041.jpg
training\n0\n0042.jpg
training\n0\n0043.jpg
training\n0\n0044.jpg
training\n0\n0045.jpg
training\n0\n0046.jpg
training\n0\n0047.jpg
training\n0\n0048.jpg
training\n0\n0049.jpg
training\n0\n0050.jpg
training\n0\n0051.jpg
training\n0\n0052.jpg
training\n0\n0053.jpg
training\n0\n0110.jpg
training\n0\n0111.jpg
training\n0\n0112.jpg
training\n0\n0113.jpg
training\n0\n0114.jpg
training\n0\n0115.jpg
training\n0\n0116.jpg
training\n0\n0117.jpg
training\n0\n0118.j

training\n3\n3161.jpg
training\n3\n3162.jpg
training\n3\n3163.jpg
training\n3\n3164.jpg
training\n3\n3165.jpg
training\n3\n3166.jpg
training\n3\n3167.jpg
training\n3\n3168.jpg
training\n3\n3169.jpg
training\n3\n3170.jpg
training\n3\n3171.jpg
training\n3\n3172.jpg
training\n4\
training\n4\n4016.jpg
training\n4\n4017.jpg
training\n4\n4018.jpg
training\n4\n4019.jpg
training\n4\n4020.jpg
training\n4\n4021.jpg
training\n4\n4022.jpg
training\n4\n4023.jpg
training\n4\n4024.jpg
training\n4\n4025.jpg
training\n4\n4026.jpg
training\n4\n4027.jpg
training\n4\n4028.jpg
training\n4\n4029.jpg
training\n4\n4030.jpg
training\n4\n4031.jpg
training\n4\n4032.jpg
training\n4\n4033.jpg
training\n4\n4034.jpg
training\n4\n4035.jpg
training\n4\n4036.jpg
training\n4\n4037.jpg
training\n4\n4038.jpg
training\n4\n4039.jpg
training\n4\n4040.jpg
training\n4\n4041.jpg
training\n4\n4042.jpg
training\n4\n4043.jpg
training\n4\n4044.jpg
training\n4\n4045.jpg
training\n4\n4046.jpg
training\n4\n4047.jpg
training\n4\n4048.j

training\n7\n7124.jpg
training\n7\n7125.jpg
training\n7\n7126.jpg
training\n7\n7127.jpg
training\n7\n7128.jpg
training\n7\n7129.jpg
training\n7\n7130.jpg
training\n7\n7131.jpg
training\n7\n7132.jpg
training\n7\n7133.jpg
training\n7\n7134.jpg
training\n7\n7135.jpg
training\n7\n7136.jpg
training\n7\n7137.jpg
training\n7\n7138.jpg
training\n7\n7139.jpg
training\n7\n7140.jpg
training\n7\n7141.jpg
training\n7\n7142.jpg
training\n7\n7143.jpg
training\n7\n7144.jpg
training\n7\n7145.jpg
training\n7\n7146.jpg
training\n7\n7147.jpg
training\n7\n7148.jpg
training\n7\n7149.jpg
training\n7\n7150.jpg
training\n7\n7151.jpg
training\n7\n7152.jpg
training\n7\n7153.jpg
training\n7\n7154.jpg
training\n7\n7155.jpg
training\n7\n7156.jpg
training\n7\n7157.jpg
training\n7\n7158.jpg
training\n7\n7159.jpg
training\n7\n7160.jpg
training\n7\n7161.jpg
training\n7\n7162.jpg
training\n7\n7163.jpg
training\n7\n7164.jpg
training\n7\n7165.jpg
training\n7\n7166.jpg
training\n7\n7167.jpg
training\n7\n7168.jpg
training\n

In [8]:
Z = []

# go through all the image locations one by one
for img_name in X.Filename:
    # read the image from location
    img = plt.imread(img_name)
    print(img_name)
    new_img = resize(img, (224, 224, 3))
    # pile it one over the other
    Z.append(new_img)
    
# convert this python list to a single numpy array
Z = np.array(Z)

training\n0\n0018.jpg
training\n0\n0019.jpg
training\n0\n0020.jpg
training\n0\n0021.jpg
training\n0\n0022.jpg
training\n0\n0023.jpg
training\n0\n0024.jpg
training\n0\n0025.jpg
training\n0\n0026.jpg
training\n0\n0027.jpg
training\n0\n0028.jpg
training\n0\n0029.jpg
training\n0\n0030.jpg
training\n0\n0031.jpg
training\n0\n0032.jpg
training\n0\n0033.jpg
training\n0\n0034.jpg
training\n0\n0035.jpg
training\n0\n0036.jpg
training\n0\n0037.jpg
training\n0\n0038.jpg
training\n0\n0039.jpg
training\n0\n0040.jpg
training\n0\n0041.jpg
training\n0\n0042.jpg
training\n0\n0043.jpg
training\n0\n0044.jpg
training\n0\n0045.jpg
training\n0\n0046.jpg
training\n0\n0047.jpg
training\n0\n0048.jpg
training\n0\n0049.jpg
training\n0\n0050.jpg
training\n0\n0051.jpg
training\n0\n0052.jpg
training\n0\n0053.jpg
training\n0\n0110.jpg
training\n0\n0111.jpg
training\n0\n0112.jpg
training\n0\n0113.jpg
training\n0\n0114.jpg
training\n0\n0115.jpg
training\n0\n0116.jpg
training\n0\n0117.jpg
training\n0\n0118.jpg
training\n

training\n3\n3067.jpg
training\n3\n3068.jpg
training\n3\n3069.jpg
training\n3\n3070.jpg
training\n3\n3071.jpg
training\n3\n3072.jpg
training\n3\n3073.jpg
training\n3\n3074.jpg
training\n3\n3075.jpg
training\n3\n3076.jpg
training\n3\n3077.jpg
training\n3\n3078.jpg
training\n3\n3110.jpg
training\n3\n3111.jpg
training\n3\n3112.jpg
training\n3\n3113.jpg
training\n3\n3114.jpg
training\n3\n3115.jpg
training\n3\n3116.jpg
training\n3\n3117.jpg
training\n3\n3118.jpg
training\n3\n3119.jpg
training\n3\n3120.jpg
training\n3\n3121.jpg
training\n3\n3122.jpg
training\n3\n3123.jpg
training\n3\n3124.jpg
training\n3\n3125.jpg
training\n3\n3126.jpg
training\n3\n3127.jpg
training\n3\n3128.jpg
training\n3\n3129.jpg
training\n3\n3130.jpg
training\n3\n3131.jpg
training\n3\n3132.jpg
training\n3\n3133.jpg
training\n3\n3134.jpg
training\n3\n3135.jpg
training\n3\n3136.jpg
training\n3\n3137.jpg
training\n3\n3138.jpg
training\n3\n3139.jpg
training\n3\n3140.jpg
training\n3\n3141.jpg
training\n3\n3142.jpg
training\n

training\n6\n6137.jpg
training\n6\n6138.jpg
training\n6\n6139.jpg
training\n6\n6140.jpg
training\n6\n6141.jpg
training\n6\n6142.jpg
training\n6\n6143.jpg
training\n6\n6144.jpg
training\n6\n6145.jpg
training\n6\n6146.jpg
training\n6\n6147.jpg
training\n6\n6148.jpg
training\n6\n6149.jpg
training\n6\n6150.jpg
training\n6\n6151.jpg
training\n6\n6152.jpg
training\n6\n6153.jpg
training\n6\n6154.jpg
training\n6\n6155.jpg
training\n6\n6156.jpg
training\n6\n6157.jpg
training\n6\n6158.jpg
training\n6\n6159.jpg
training\n6\n6160.jpg
training\n6\n6161.jpg
training\n7\n7019.jpg
training\n7\n702.jpg
training\n7\n7020.jpg
training\n7\n7021.jpg
training\n7\n7022.jpg
training\n7\n7023.jpg
training\n7\n7024.jpg
training\n7\n7025.jpg
training\n7\n7026.jpg
training\n7\n7027.jpg
training\n7\n7028.jpg
training\n7\n7029.jpg
training\n7\n7030.jpg
training\n7\n7031.jpg
training\n7\n7032.jpg
training\n7\n7033.jpg
training\n7\n7034.jpg
training\n7\n7035.jpg
training\n7\n7036.jpg
training\n7\n7037.jpg
training\n7

In [9]:
Z.shape

(1097, 224, 224, 3)

In [10]:
Z = Z / Z.max()

In [14]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
X['Label']= label_encoder.fit_transform(X['Label']) 

In [15]:
y = X.Label.values

In [21]:
from keras.utils import to_categorical
y = to_categorical(y)

In [25]:
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [22]:
X_train, X_valid, Y_train, Y_valid=train_test_split(Z,y,test_size=0.3, random_state=42)

In [30]:
model = Sequential()
    
model.add(InputLayer(input_shape=(224, 224, 3)))

model.add(Conv2D(25, (5, 5), activation='relu', strides=(1, 1), padding='valid'))
model.add(Conv2D(50, (5, 5), activation='relu', strides=(1, 1), padding='valid'))

model.add(Flatten())

model.add(Dense(units=100, activation='sigmoid'))
model.add(Dense(units=10, activation='sigmoid'))

In [31]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 220, 220, 25)      1900      
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 216, 216, 50)      31300     
_________________________________________________________________
flatten_3 (Flatten)          (None, 2332800)           0         
_________________________________________________________________
dense_5 (Dense)              (None, 100)               233280100 
_________________________________________________________________
dense_6 (Dense)              (None, 10)                1010      
Total params: 233,314,310
Trainable params: 233,314,310
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.compile(optimizer='sgd', metrics=['accuracy'], loss='categorical_crossentropy')

In [34]:
model.fit(X_train, Y_train, epochs=15, validation_data=(X_valid, Y_valid))

Train on 767 samples, validate on 330 samples
Epoch 1/15
767/767 [==============================] - 145s 189ms/step - loss: 2.2463 - accuracy: 0.1525 - val_loss: 2.1994 - val_accuracy: 0.1667
Epoch 2/15
767/767 [==============================] - 148s 193ms/step - loss: 2.1479 - accuracy: 0.2047 - val_loss: 2.1211 - val_accuracy: 0.2424
Epoch 3/15
767/767 [==============================] - 147s 192ms/step - loss: 2.0165 - accuracy: 0.2973 - val_loss: 2.0532 - val_accuracy: 0.2091
Epoch 4/15
767/767 [==============================] - 151s 197ms/step - loss: 1.9321 - accuracy: 0.3598 - val_loss: 2.0001 - val_accuracy: 0.2939
Epoch 5/15
767/767 [==============================] - 147s 192ms/step - loss: 1.8465 - accuracy: 0.4120 - val_loss: 1.9222 - val_accuracy: 0.3485
Epoch 6/15
767/767 [==============================] - 156s 204ms/step - loss: 1.7474 - accuracy: 0.4837 - val_loss: 1.9052 - val_accuracy: 0.3545
Epoch 7/15
767/767 [==============================] - 159s 207ms/step - loss: 

In [35]:
predictions = model.predict_classes(X_valid)
predictions

array([9, 2, 9, 0, 3, 9, 1, 0, 8, 4, 2, 2, 9, 1, 5, 2, 8, 1, 4, 6, 9, 2,
       3, 1, 9, 5, 1, 7, 2, 3, 9, 4, 3, 2, 0, 7, 3, 1, 6, 6, 7, 1, 6, 9,
       9, 2, 3, 3, 4, 6, 1, 1, 1, 5, 5, 2, 6, 1, 6, 3, 2, 0, 2, 2, 9, 7,
       9, 3, 3, 3, 6, 5, 1, 2, 7, 5, 9, 7, 5, 4, 6, 1, 4, 6, 5, 6, 9, 9,
       8, 4, 7, 3, 7, 1, 9, 5, 9, 4, 2, 3, 6, 1, 9, 3, 2, 9, 4, 7, 2, 7,
       8, 0, 6, 2, 1, 7, 3, 6, 3, 2, 9, 5, 9, 3, 7, 7, 8, 5, 6, 9, 3, 6,
       3, 3, 8, 5, 2, 3, 4, 1, 2, 9, 3, 5, 9, 7, 6, 7, 6, 9, 3, 2, 9, 6,
       7, 7, 9, 3, 6, 0, 0, 7, 1, 5, 9, 6, 9, 5, 8, 5, 9, 2, 3, 9, 9, 3,
       2, 5, 1, 9, 2, 1, 1, 9, 1, 4, 9, 7, 5, 2, 1, 3, 7, 3, 4, 9, 9, 2,
       0, 6, 9, 8, 4, 5, 2, 6, 8, 6, 6, 9, 2, 3, 4, 8, 9, 1, 6, 3, 7, 2,
       0, 0, 5, 0, 7, 3, 6, 4, 1, 6, 9, 3, 6, 2, 3, 4, 3, 3, 9, 6, 0, 6,
       7, 5, 2, 9, 3, 5, 7, 9, 7, 1, 5, 9, 3, 7, 1, 3, 2, 9, 5, 3, 4, 6,
       3, 6, 4, 7, 6, 3, 6, 6, 2, 1, 0, 4, 0, 3, 6, 8, 4, 7, 2, 1, 4, 2,
       9, 2, 9, 1, 4, 3, 3, 2, 7, 4, 7, 8, 1, 5, 3,

In [56]:
preddata = []

for file_name in glob.iglob('validation\\n4\\*.*', recursive=True):
    preddummy = []
    pred_img = plt.imread(file_name)
    pred_new_img = resize(pred_img, (224, 224, 3))
    preddata.append(pred_new_img)
    preddummy.append(pred_new_img)
    preddummydata = np.array(preddummy)
    predictionsdummy = model.predict_classes(preddummydata)
    print(file_name+","+str(predictionsdummy))
preddata = np.array(preddata)

validation\n4\n400.jpg,[2]
validation\n4\n401.jpg,[4]
validation\n4\n4010.jpg,[7]
validation\n4\n4011.jpg,[6]
validation\n4\n4012.jpg,[4]
validation\n4\n4013.jpg,[3]
validation\n4\n4014.jpg,[2]
validation\n4\n4015.jpg,[2]
validation\n4\n402.jpg,[6]
validation\n4\n403.jpg,[4]
validation\n4\n404.jpg,[4]
validation\n4\n405.jpg,[6]
validation\n4\n406.jpg,[4]
validation\n4\n407.jpg,[1]
validation\n4\n408.jpg,[2]
validation\n4\n409.jpg,[4]
validation\n4\n410.jpg,[3]
validation\n4\n411.jpg,[4]
validation\n4\n412.jpg,[4]
validation\n4\n413.jpg,[5]
validation\n4\n414.jpg,[7]
validation\n4\n415.jpg,[9]
validation\n4\n416.jpg,[3]
validation\n4\n417.jpg,[4]
validation\n4\n418.jpg,[9]
validation\n4\n419.jpg,[4]


In [64]:
predictions = model.predict_classes(preddata)
np.count_nonzero(predictions == 4)

10

In [63]:
np.bincount(predictions)


array([ 0,  1,  4,  3, 10,  1,  3,  2,  0,  2], dtype=int64)